name: env
description: Smart produce management and food waste reduction app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # UI Components
  cupertino_icons: ^1.0.6

  # Charts
  fl_chart: ^0.66.0

  # HTTP requests
  http: ^1.1.2

  # Google Generative AI (Gemini)
  google_generative_ai: ^0.4.3

  # Firebase (removed - using direct GCP calls)
  # firebase_core: ^2.4.1
  # firebase_storage: ^11.2.6

  # Image handling
  image_picker: ^1.0.4
  camera: ^0.10.5

  # Local storage
  shared_preferences: ^2.2.2

  # Icons
  lucide_icons: ^0.257.0

  # Fonts
  google_fonts: ^6.1.0

  # Date handling
  intl: ^0.19.0

  # Path utilities
  # path: ^1.8.3  # Removed - no longer needed

  # Maps and Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Json serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
